# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"
Vagrant.configure(VAGRANT_API_VERSION) do |config|

  config.ssh.insert_key = false
  VAGRANT_BOX_IMAGE = "ubuntu/xenial64"
  MACHINE_BASE_IP = "192.168.33."
  MACHINE_COUNT = 3

  (1...MACHINE_COUNT).each do |machine_id|
    config.vm.define "machine0#{machine_id}" do |machine|
      machine.vm.hostname = "machine0#{machine_id}"
      machine.vm.box = VAGRANT_BOX_IMAGE
      machine.vm.network "private_network", ip: "#{MACHINE_BASE_IP}#{11 + machine_id}"
      machine.vm.provider :virtualbox  do |vb|
        # vb.gui = true
        vb.customize ["modifyvm", :id, "--name", "machine0#{machine_id}"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--memory", 1024]
        # vb.customize ["modifyvm", :id, "--cableconnected1", "off"]
      end
      if machine_id == MACHINE_COUNT
        machine.vm.provision :shell, inline: "echo Great stuff!"
      end
    end
  end

  config.vm.define :ansiblecntrl do |ansiblecntrl|
    ansiblecntrl.vm.hostname = "ansiblecntrl"
    ansiblecntrl.vm.box = VAGRANT_BOX_IMAGE
    ansiblecntrl.vm.network "private_network", ip: "#{MACHINE_BASE_IP}#{10}"
    ansiblecntrl.vm.synced_folder ".", "/vagrant", type: "nfs"

    ansiblecntrl.vm.provider "virtualbox" do |vb|
      # vb.gui = true
      vb.customize ["modifyvm", :id, "--name", "ansiblecntrl"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--memory", 1024]
    end

    ansiblecntrl.vm.provision :ansible_local do |ansible|
      ansible.playbook       = "playbook.yml"
      ansible.verbose        = true
      ansible.install        = true
      ansible.limit          = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "./inventory/inventory.ini"
    end
    ansiblecntrl.vm.provision "shell", inline: <<-SHELL
      echo "Running ansible control successfully"
    SHELL
  end

end
